message: hello there!

opentracing.jaeger.http-sender.url: http://jaeger:14268/api/traces

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    concurrency: 1
    maxConcurrency: 5