message: hello there!

spring:
  zipkin.baseUrl: http://jaeger:9411/

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    concurrency: 1
    maxConcurrency: 5