management:
  context-path: /admin

logging:
  level:
    org.springframework.cloud: 'DEBUG'
spring:
   data:
   mongodb:
     user: ms-covid
     password: mscovid
     uri: mongodb://ms-covid-mongo:27017/ms-covid

rabbitmq:
  covid:
    queue: covid19
