server:
  port: 8888

management:
  context-path: /admin

logging:
  level:
    org.springframework.cloud: 'DEBUG'
spring:
   data:
     mongodb:
       uri: mongodb://ms-covid-mongo:27017/ms-covid

rabbitmq:
  covid:
    queue: covid19
