server:
  port: 8889

management:
  context-path: /admin

logging:
  level:
    org.springframework.cloud: 'DEBUG'
spring:
   data:
     mongodb:
       uri: mongodb://localhost:27017/ms-covid

rabbitmq:
 host: localhost
 port: 5672
 username: guest
 password: guest
 virtualHost: /
 concurrency: 1
 maxConcurrency: 5
 covid:
   queue: covid19
