server:
  port: 8889

management:
  context-path: /admin

logging:
  level:
    org.springframework.cloud: 'DEBUG'
spring:
   data:
   mongodb:
     user: ms-covid
     password: mscovid
     uri: mongodb://localhost:27017/ms-TODO
