server:
  port: 8889

management:
  context-path: /admin

logging:
  level:
    org.springframework.cloud: 'DEBUG'
spring:
   data:
   mongodb:
     user: ms-covid
     password: mscovid
     uri: mongodb://localhost:27017/ms-TODO
   rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    concurrency: 1
    maxConcurrency: 5

rabbitmq:
  covid:
    queue: covid19
eureka:
  instance:
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
